In [14]:
"""
AUTHOR:KRISTAL SHRESTHA
DATE:6/19/2024
PURPOSE:argsort,argmin,argmax and others
"""

'\nAUTHOR:KRISTAL SHRESTHA\nDATE:6/19/2024\nPURPOSE:argsort,argmin,argmax and others\n'

In [15]:
import numpy as np

In [16]:
a=np.arange(6)

In [17]:
a

array([0, 1, 2, 3, 4, 5])

In [18]:
b=np.array([11,23,2,45,78,7,7,764,4,34343,4,343434,34,33,32])

In [19]:
b.shape

(15,)

In [20]:
b=b.reshape(3,5)

In [21]:
b

array([[    11,     23,      2,     45,     78],
       [     7,      7,    764,      4,  34343],
       [     4, 343434,     34,     33,     32]])

In [22]:
np.argsort(b)

array([[2, 0, 1, 3, 4],
       [3, 0, 1, 2, 4],
       [0, 4, 3, 2, 1]])

In [27]:
np.argsort(a)

array([0, 1, 2, 3, 4, 5])

In [23]:
np.argmin(b)

np.int64(2)

In [24]:
np.argmin(a)

np.int64(0)

In [25]:
np.argmax(b)

np.int64(11)

In [26]:
np.argmax(a)

np.int64(5)