## BASIC FUNCTIONS

In [22]:
import numpy as np
array1=np.array([[3,2,5,7,0.5],[1,12,3,4,5]],dtype='int64')
print(array1)
print(type(array1))

[[ 3  2  5  7  0]
 [ 1 12  3  4  5]]
<class 'numpy.ndarray'>


In [23]:
array1.shape

(2, 5)

In [24]:
array1.dtype

dtype('int64')

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

In [26]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [28]:
np.ones(6).dtype

dtype('float64')

In [29]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
np.array([1, 2, 3, 4])
np.array([[1, 2], [3, 4]])
np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])

In [32]:
array1*array1

array([[  9,   4,  25,  49,   0],
       [  1, 144,   9,  16,  25]])

In [33]:
array1+array1

array([[ 6,  4, 10, 14,  0],
       [ 2, 24,  6,  8, 10]])

In [34]:
array1-array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
array1/array1

C:\Users\Kristal\AppData\Local\Temp\ipykernel_4548\3963778006.py:1: RuntimeWarning: invalid value encountered in divide
  array1/array1


array([[ 1.,  1.,  1.,  1., nan],
       [ 1.,  1.,  1.,  1.,  1.]])

In [36]:
array1**array1

array([[           27,             4,          3125,        823543,
                    1],
       [            1, 8916100448256,            27,           256,
                 3125]])

In [37]:
12**12

8916100448256

In [40]:
np.array([12.0**12])

array([8.91610045e+12])

In [41]:
np.array([12.0**12],dtype='int64')

array([8916100448256])

In [42]:
1/array1

C:\Users\Kristal\AppData\Local\Temp\ipykernel_4548\2387133254.py:1: RuntimeWarning: divide by zero encountered in divide
  1/array1


array([[0.33333333, 0.5       , 0.2       , 0.14285714,        inf],
       [1.        , 0.08333333, 0.33333333, 0.25      , 0.2       ]])

## SLICING

In [46]:
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])

In [50]:
array2=np.array([5,6,10,4,11,2,11])

In [51]:
array2[4:6]

array([11,  2])

In [52]:
arr = array2[4:6]

In [53]:
arr

array([11,  2])

In [54]:
arr[0]=9

In [55]:
array2

array([ 5,  6, 10,  4,  9,  2, 11])

In [56]:
arr1=array2.copy()

In [57]:
arr1

array([ 5,  6, 10,  4,  9,  2, 11])

In [58]:
arr1[0]=11

In [59]:
array2

array([ 5,  6, 10,  4,  9,  2, 11])

In [60]:
arr1

array([11,  6, 10,  4,  9,  2, 11])

In [61]:
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])

In [62]:
array1[0]

array([3, 2, 5, 7, 0])

In [63]:
array1[0,3]

np.int64(7)