In [1]:
"""
AUTHOR:KRISTAL SHRESTHA
DATE:6/19/2024
PURPOSE:LEARNING NUMPY AXIS SORTING
"""

'\nAUTHOR:KRISTAL SHRESTHA\nDATE:6/19/2024\nPURPOSE:LEARNING NUMPY AXIS SORTING\n'

In [3]:
import numpy as np
array1=np.array([[1,2,3],
          [4,5,6]])

In [5]:
array1.sum(axis=1)

array([ 6, 15])

In [6]:
array1.sum(axis=0)

array([5, 7, 9])

In [7]:
array2=np.array([[7,8,9],
          [2,8,0]])

In [8]:
array2.transpose()

array([[7, 2],
       [8, 8],
       [9, 0]])

In [12]:
array2

array([[7, 8, 9],
       [2, 8, 0]])

In [11]:
array1.dot(array2.transpose())

array([[ 50,  18],
       [122,  48]])

In [15]:
np.dot(array1,array2.transpose())

array([[ 50,  18],
       [122,  48]])

In [14]:
np.cross(array1,array2)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [ ]:
dir(np)

In [19]:
array3=np.array([[11,2,13],
          [14,25,6]])


In [20]:
np.sort(array3)

array([[ 2, 11, 13],
       [ 6, 14, 25]])

In [21]:
array3

array([[11,  2, 13],
       [14, 25,  6]])

In [22]:
np.sort(array3,axis=0)

array([[11,  2,  6],
       [14, 25, 13]])

In [25]:
%timeit np.sort(array3,axis=0,kind='mergesort')

2.78 μs ± 97.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [27]:
%timeit np.sort(array3,axis=0,kind='quicksort')

2.94 μs ± 74.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [28]:
%timeit np.sort(array3,axis=0,kind='heapsort')

2.68 μs ± 124 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
